# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"`\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x15\n\rcreation_time\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\"#\n\x10LocationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0fLocationService\x12G\n\x0cSendLocation\x12\x19.location.LocationRequest\x1a\x1a.location.LocationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOCATIONREQUEST']._serialized_start=28
  _globals['_LOCATIONREQUEST']._serialized_end=124
  _globals['_LOCATIONRESPONSE']._serialized_start=126
  _globals['_LOCATIONRESPONSE']._serialized_end=161
  _globals['_LOCATIONSERVICE']._serialized_start=163
  _globals['_LOCATIONSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
