apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection
  name: connection-service
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 31000
  selector:
    service: connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection
  name: connection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection
  template:
    metadata:
      labels:
        service: connection
    spec:
      containers:
      - image: nembo009/connection-service:1.0
        name: connection
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
