apiVersion: v1
kind: Service
metadata:
  labels:
    service: location
  name: location-service
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 31001
  selector:
    service: location
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location
  name: location-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location
  template:
    metadata:
      labels:
        service: location
    spec:
      containers:
      - image: nembo009/location-service:1.0
        name: location
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
