swagger: '2.0'
info:
  version: '1.0'
  title: 'Persons Retrieval API'
  description: 'APIs designed to provide operations related to persons, including listing all registered individuals.'

paths:
  /persons:
    get:
      tags:
      - 'Persons'
      summary: 'Retrieve all registered persons'
      description: 'Fetches a list containing details of all persons registered in the system.'
      responses:
        '200':
          description: 'List of persons retrieved successfully'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Person'
              description: 'A person with their respective details.'

definitions:
  Person:
    description: 'Data structure representing the individual details of a person'
    type: 'object'
    properties:
      id:
        type: 'integer'
        description: 'Unique identifier representing a specific person'
      first_name:
        type: 'string'
        description: 'First name of the individual'
      last_name:
        type: 'string'
        description: 'Last name of the individual'
      company_name:
        type: 'string'
        description: 'Company or organization with which the person is associated'
